apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hwkc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-hwkc@sha256:924620515c36bb1244464e7db199fdfccab31d47cfc1d454c5c9502800fb999b
        name: my-nodejs
        resources: {}
status: {}
